// examples/nextjs/src/components/skeleton-text.tsx
import { Skeleton } from "@line/abc-def-react/skeleton";

export function SkeletonText() {
  return (
    <div className="flex w-full max-w-xs flex-col gap-2">
      <Skeleton className="h-4 w-full" />
      <Skeleton className="h-4 w-full" />
      <Skeleton className="h-4 w-3/4" />
    </div>
  );
}

// examples/vue-vite/src/examples/skeleton/SkeletonText.vue
<script setup lang="ts">
import { Skeleton } from "@line/abc-def-vue/skeleton";

import { Example } from "@/registry/bases/reka/components/example";
</script>

<template>
  <Example title="Text">
    <div class="flex w-full flex-col gap-2">
      <Skeleton class="h-4 w-full" />
      <Skeleton class="h-4 w-full" />
      <Skeleton class="h-4 w-3/4" />
    </div>
  </Example>
</template>
