// examples/nextjs/src/components/checkbox-basic.tsx
import { Checkbox } from "@line/abc-def-react/checkbox";
import { Field, FieldGroup, FieldLabel } from "@line/abc-def-react/field";

export function CheckboxBasic() {
  return (
    <FieldGroup className="mx-auto w-56">
      <Field orientation="horizontal">
        <Checkbox id="terms-checkbox-basic" name="terms-checkbox-basic" />
        <FieldLabel htmlFor="terms-checkbox-basic">
          Accept terms and conditions
        </FieldLabel>
      </Field>
    </FieldGroup>
  );
}

// examples/vue-vite/src/examples/checkbox/CheckboxBasic.vue
<script setup lang="ts">
import { Checkbox } from "@line/abc-def-vue/checkbox";
import { Field, FieldLabel } from "@line/abc-def-vue/field";

import { Example } from "@/components/example";
</script>

<template>
  <Example title="Basic">
    <Field orientation="horizontal">
      <Checkbox id="terms" />
      <FieldLabel html-for="terms"> Accept terms and conditions </FieldLabel>
    </Field>
  </Example>
</template>
