// examples/nextjs/src/components/input-form.tsx
import { Button } from "@line/abc-def-react/button";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@line/abc-def-react/field";
import { Input } from "@line/abc-def-react/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@line/abc-def-react/select";

export function InputForm() {
  return (
    <form className="w-full max-w-sm">
      <FieldGroup>
        <Field>
          <FieldLabel htmlFor="form-name">Name</FieldLabel>
          <Input
            id="form-name"
            type="text"
            placeholder="Evil Rabbit"
            required
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="form-email">Email</FieldLabel>
          <Input id="form-email" type="email" placeholder="john@example.com" />
          <FieldDescription>
            We&apos;ll never share your email with anyone.
          </FieldDescription>
        </Field>
        <div className="grid grid-cols-2 gap-4">
          <Field>
            <FieldLabel htmlFor="form-phone">Phone</FieldLabel>
            <Input id="form-phone" type="tel" placeholder="+1 (555) 123-4567" />
          </Field>
          <Field>
            <FieldLabel htmlFor="form-country">Country</FieldLabel>
            <Select defaultValue="us">
              <SelectTrigger id="form-country">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="us">United States</SelectItem>
                <SelectItem value="uk">United Kingdom</SelectItem>
                <SelectItem value="ca">Canada</SelectItem>
              </SelectContent>
            </Select>
          </Field>
        </div>
        <Field>
          <FieldLabel htmlFor="form-address">Address</FieldLabel>
          <Input id="form-address" type="text" placeholder="123 Main St" />
        </Field>
        <Field orientation="horizontal">
          <Button type="button" variant="outline">
            Cancel
          </Button>
          <Button type="submit">Submit</Button>
        </Field>
      </FieldGroup>
    </form>
  );
}

// examples/vue-vite/src/examples/input/InputForm.vue
<script setup lang="ts">
import { Button } from "@line/abc-def-vue/button";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@line/abc-def-vue/field";
import { Input } from "@line/abc-def-vue/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@line/abc-def-vue/select";
</script>

<template>
  <form class="w-full">
    <FieldGroup>
      <Field>
        <FieldLabel html-for="form-name"> Name </FieldLabel>
        <Input id="form-name" type="text" placeholder="John Doe" />
      </Field>
      <Field>
        <FieldLabel html-for="form-email"> Email </FieldLabel>
        <Input id="form-email" type="email" placeholder="john@example.com" />
        <FieldDescription>
          We'll never share your email with anyone.
        </FieldDescription>
      </Field>
      <div class="grid grid-cols-2 gap-4">
        <Field>
          <FieldLabel html-for="form-phone"> Phone </FieldLabel>
          <Input id="form-phone" type="tel" placeholder="+1 (555) 123-4567" />
        </Field>
        <Field>
          <FieldLabel html-for="form-country"> Country </FieldLabel>
          <Select default-value="us">
            <SelectTrigger id="form-country">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="us"> United States </SelectItem>
              <SelectItem value="uk"> United Kingdom </SelectItem>
              <SelectItem value="ca"> Canada </SelectItem>
            </SelectContent>
          </Select>
        </Field>
      </div>
      <Field>
        <FieldLabel html-for="form-address"> Address </FieldLabel>
        <Input id="form-address" type="text" placeholder="123 Main St" />
      </Field>
      <Field orientation="horizontal">
        <Button type="button" variant="outline"> Cancel </Button>
        <Button type="submit"> Submit </Button>
      </Field>
    </FieldGroup>
  </form>
</template>
