// examples/react-vite/src/App.tsx
import {
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  Input,
} from "@abc-def/react";

export default function App() {
  return (
    <main className="bg-background text-foreground min-h-screen px-6 py-16">
      <div className="mx-auto flex w-full max-w-3xl flex-col gap-6">
        <Card>
          <CardHeader>
            <CardTitle>React mirrors the shared button contract</CardTitle>
            <p className="abc-text-dim">
              Variants, sizes, and classes come from <code>@abc-def/styles/css</code>.
            </p>
          </CardHeader>
          <CardContent>
            <Input placeholder="Type into the shared input component" />
            <div className="card-actions">
              <Button variant="outline" size="sm">Outline</Button>
              <Button variant="secondary">Secondary</Button>
              <Button variant="ghost">Ghost</Button>
              <Button variant="link">Link</Button>
              <Button asChild variant="link">
                <a href="/docs">Docs</a>
              </Button>
              <Button variant="destructive">Delete</Button>
              <Button>Default</Button>
            </div>
            <div className="card-actions">
              <Button size="sm">Small</Button>
              <Button>Default</Button>
              <Button size="lg">Large</Button>
              <Button size="icon" aria-label="Add item">
                +
              </Button>
              <Button size="icon-sm" aria-label="Add small item">
                +
              </Button>
              <Button size="icon-lg" aria-label="Add large item">
                +
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}

// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { Button, Separator } from "@abc-def/vue";
import { Plus } from "lucide-vue-next";

const VARIANTS = [
  null,
  "default",
  "destructive",
  "ghost",
  "link",
  "outline",
] as const;

const SIZES = [null, "xs", "sm", "default", "lg", "xl"] as const;
const ICON_SIZES = [
  "icon-xs",
  "icon-sm",
  "icon",
  "icon-lg",
  "icon-xl",
] as const;
const ROUNDED = [null, "xs", "sm", "default", "lg", "xl"] as const;
</script>

<template>
  <main className="bg-background text-foreground min-h-screen px-6 py-16">
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-6">
      <div className="flex gap-2">
        <Button v-for="variant in VARIANTS" :key="variant" :variant="variant">
          {{ variant ?? "null" }}
        </Button>
      </div>
      <div className="flex gap-2">
        <Button v-for="size in SIZES" :key="size" :size="size">
          size - {{ size ?? "null" }}
        </Button>
      </div>
      <div className="flex gap-2">
        <Button v-for="size in ICON_SIZES" :key="size" :size="size">
          <Plus />
        </Button>
      </div>
      <div className="flex gap-2">
        <Button v-for="rounded in ROUNDED" :key="rounded" :rounded="rounded">
          rounded - {{ rounded ?? "null" }}
        </Button>
      </div>
      <div class="flex h-5 items-center space-x-4 text-sm">
        <div>Blog</div>
        <Separator orientation="vertical" />
        <div>Docs</div>
        <Separator orientation="vertical" />
        <div>Source</div>
      </div>
    </div>
  </main>
</template>
