// examples/nextjs/src/components/slider-vertical.tsx
import { Slider } from "@line/abc-def-react/slider";

export function SliderVertical() {
  return (
    <div className="mx-auto flex w-full max-w-xs items-center justify-center gap-6">
      <Slider
        defaultValue={[50]}
        max={100}
        step={1}
        orientation="vertical"
        className="h-40"
      />
      <Slider
        defaultValue={[25]}
        max={100}
        step={1}
        orientation="vertical"
        className="h-40"
      />
    </div>
  );
}

// examples/vue-vite/src/examples/slider/SliderVertical.vue
<script setup lang="ts">
import { Slider } from "@line/abc-def-vue/slider";
</script>

<template>
  <div class="flex items-center gap-6">
    <Slider
      :default-value="[50]"
      :max="100"
      :step="1"
      orientation="vertical"
      class="h-40"
    />
    <Slider
      :default-value="[25]"
      :max="100"
      :step="1"
      orientation="vertical"
      class="h-40"
    />
  </div>
</template>
