// examples/nextjs/src/components/toggle-group-outline.tsx
import { ToggleGroup, ToggleGroupItem } from "@line/abc-def-react/toggle-group";

export function ToggleGroupOutline() {
  return (
    <ToggleGroup variant="outline" type="single" defaultValue="all">
      <ToggleGroupItem value="all" aria-label="Toggle all">
        All
      </ToggleGroupItem>
      <ToggleGroupItem value="missed" aria-label="Toggle missed">
        Missed
      </ToggleGroupItem>
    </ToggleGroup>
  );
}

// examples/vue-vite/src/examples/toggle-group/ToggleGroupOutline.vue
<script setup lang="ts">
import { ToggleGroup, ToggleGroupItem } from "@line/abc-def-vue/toggle-group";
</script>

<template>
  <ToggleGroup variant="outline" type="single" default-value="all">
    <ToggleGroupItem value="all" aria-label="Toggle all"> All </ToggleGroupItem>
    <ToggleGroupItem value="missed" aria-label="Toggle missed">
      Missed
    </ToggleGroupItem>
  </ToggleGroup>
</template>
