// examples/nextjs/src/components/carousel-multiple.tsx
import { Card, CardContent } from "@line/abc-def-react/card";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@line/abc-def-react/carousel";

export function CarouselMultiple() {
  return (
    <Carousel
      className="mx-auto max-w-xs sm:max-w-sm"
      opts={{
        align: "start",
      }}
    >
      <CarouselContent>
        {Array.from({ length: 5 }).map((_, index) => (
          <CarouselItem key={index} className="sm:basis-1/2 lg:basis-1/3">
            <div className="p-1">
              <Card>
                <CardContent className="flex aspect-square items-center justify-center p-6">
                  <span className="text-3xl font-semibold">{index + 1}</span>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
        ))}
      </CarouselContent>
      <CarouselPrevious className="hidden sm:inline-flex" />
      <CarouselNext className="hidden sm:inline-flex" />
    </Carousel>
  );
}

// examples/vue-vite/src/examples/carousel/CarouselMultiple.vue
<script setup lang="ts">
import { Card, CardContent } from "@line/abc-def-vue/card";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@line/abc-def-vue/carousel";

import { Example } from "@/components/example";
</script>

<template>
  <Example title="Multiple">
    <Carousel
      class="mx-auto max-w-xs sm:max-w-sm"
      :opts="{
        align: 'start',
      }"
    >
      <CarouselContent>
        <CarouselItem
          v-for="index in 5"
          :key="index"
          class="sm:basis-1/2 lg:basis-1/3"
        >
          <div class="p-1">
            <Card>
              <CardContent
                class="flex aspect-square items-center justify-center p-6"
              >
                <span class="text-3xl font-semibold">{{ index }}</span>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious class="hidden sm:inline-flex" />
      <CarouselNext class="hidden sm:inline-flex" />
    </Carousel>
  </Example>
</template>
