// examples/nextjs/src/components/switch-sizes.tsx
import { Field, FieldGroup, FieldLabel } from "@line/abc-def-react/field";
import { Switch } from "@line/abc-def-react/switch";

export function SwitchSizes() {
  return (
    <FieldGroup className="w-full max-w-[10rem]">
      <Field orientation="horizontal">
        <Switch id="switch-size-sm" size="sm" />
        <FieldLabel htmlFor="switch-size-sm">Small</FieldLabel>
      </Field>
      <Field orientation="horizontal">
        <Switch id="switch-size-default" size="default" />
        <FieldLabel htmlFor="switch-size-default">Default</FieldLabel>
      </Field>
    </FieldGroup>
  );
}

// examples/vue-vite/src/examples/switch/SwitchSizes.vue
<script setup lang="ts">
import { Label } from "@line/abc-def-vue/label";
import { Switch } from "@line/abc-def-vue/switch";
</script>

<template>
  <div class="flex flex-col gap-12">
    <div class="flex items-center gap-2">
      <Switch id="switch-size-sm" size="sm" />
      <Label html-for="switch-size-sm">Small</Label>
    </div>
    <div class="flex items-center gap-2">
      <Switch id="switch-size-default" size="default" />
      <Label html-for="switch-size-default">Default</Label>
    </div>
  </div>
</template>
