// examples/nextjs/src/components/toggle-disabled.tsx
import { Toggle } from "@line/abc-def-react/toggle";

export function ToggleDisabled() {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <Toggle aria-label="Toggle disabled" disabled>
        Disabled
      </Toggle>
      <Toggle variant="outline" aria-label="Toggle disabled outline" disabled>
        Disabled
      </Toggle>
    </div>
  );
}

// examples/vue-vite/src/examples/toggle/ToggleDisabled.vue
<script setup lang="ts">
import { Toggle } from "@line/abc-def-vue/toggle";
</script>

<template>
  <div class="flex flex-wrap items-center gap-2">
    <Toggle aria-label="Toggle disabled" :disabled="true"> Disabled </Toggle>
    <Toggle
      variant="outline"
      aria-label="Toggle disabled outline"
      :disabled="true"
    >
      Disabled
    </Toggle>
  </div>
</template>
