// examples/nextjs/src/components/toggle-sizes.tsx
import { Toggle } from "@line/abc-def-react/toggle";

export function ToggleSizes() {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <Toggle variant="outline" aria-label="Toggle small" size="sm">
        Small
      </Toggle>
      <Toggle variant="outline" aria-label="Toggle default" size="default">
        Default
      </Toggle>
      <Toggle variant="outline" aria-label="Toggle large" size="lg">
        Large
      </Toggle>
    </div>
  );
}

// examples/vue-vite/src/examples/toggle/ToggleSizes.vue
<script setup lang="ts">
import { Toggle } from "@line/abc-def-vue/toggle";
</script>

<template>
  <div class="flex flex-wrap items-center gap-2">
    <Toggle variant="outline" aria-label="Toggle small" size="sm">
      Small
    </Toggle>
    <Toggle variant="outline" aria-label="Toggle default" size="default">
      Default
    </Toggle>
    <Toggle variant="outline" aria-label="Toggle large" size="lg">
      Large
    </Toggle>
  </div>
</template>
