// examples/nextjs/src/components/pagination-simple.tsx
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
} from "@line/abc-def-react/pagination";

export function PaginationSimple() {
  return (
    <Pagination>
      <PaginationContent>
        <PaginationItem>
          <PaginationLink href="#">1</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#" isActive>
            2
          </PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">3</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">4</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">5</PaginationLink>
        </PaginationItem>
      </PaginationContent>
    </Pagination>
  );
}

// examples/vue-vite/src/examples/pagination/PaginationSimple.vue
<script setup lang="ts">
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
} from "@line/abc-def-vue/pagination";
</script>

<template>
  <Pagination>
    <PaginationContent>
      <PaginationItem>
        <PaginationLink href="#"> 1 </PaginationLink>
      </PaginationItem>
      <PaginationItem>
        <PaginationLink href="#" :is-active="true"> 2 </PaginationLink>
      </PaginationItem>
      <PaginationItem>
        <PaginationLink href="#"> 3 </PaginationLink>
      </PaginationItem>
      <PaginationItem>
        <PaginationLink href="#"> 4 </PaginationLink>
      </PaginationItem>
      <PaginationItem>
        <PaginationLink href="#"> 5 </PaginationLink>
      </PaginationItem>
    </PaginationContent>
  </Pagination>
</template>
