// examples/nextjs/src/components/combobox-invalid.tsx
"use client";

import {
  Combobox,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem,
  ComboboxList,
} from "@line/abc-def-react/combobox";

const frameworks = [
  "Next.js",
  "SvelteKit",
  "Nuxt.js",
  "Remix",
  "Astro",
] as const;

export function ComboboxInvalid() {
  return (
    <Combobox items={frameworks}>
      <ComboboxInput placeholder="Select a framework" aria-invalid="true" />
      <ComboboxContent>
        <ComboboxEmpty>No items found.</ComboboxEmpty>
        <ComboboxList>
          {(item) => (
            <ComboboxItem key={item} value={item}>
              {item}
            </ComboboxItem>
          )}
        </ComboboxList>
      </ComboboxContent>
    </Combobox>
  );
}

// examples/vue-vite/src/examples/combobox/ComboboxInvalid.vue
<script setup lang="ts">
import {
  Combobox,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem,
  ComboboxList,
  ComboboxViewport,
} from "@line/abc-def-vue/combobox";
import {
  Field,
  FieldDescription,
  FieldError,
  FieldLabel,
} from "@line/abc-def-vue/field";

import { Example } from "@/registry/bases/reka/components/example";

const frameworks = ["Next.js", "SvelteKit", "Nuxt.js", "Remix", "Astro"];
</script>

<template>
  <Example title="Invalid">
    <div class="flex flex-col gap-4">
      <Combobox :items="frameworks">
        <ComboboxInput placeholder="Select a framework" :aria-invalid="true" />
        <ComboboxList>
          <ComboboxViewport>
            <ComboboxEmpty>No items found.</ComboboxEmpty>
            <ComboboxItem v-for="item in frameworks" :key="item" :value="item">
              {{ item }}
            </ComboboxItem>
          </ComboboxViewport>
        </ComboboxList>
      </Combobox>
      <Field data-invalid>
        <FieldLabel html-for="combobox-framework-invalid">
          Framework
        </FieldLabel>
        <Combobox :items="frameworks">
          <ComboboxInput
            id="combobox-framework-invalid"
            placeholder="Select a framework"
            :aria-invalid="true"
          />
          <ComboboxList>
            <ComboboxViewport>
              <ComboboxEmpty>No items found.</ComboboxEmpty>
              <ComboboxItem
                v-for="item in frameworks"
                :key="item"
                :value="item"
              >
                {{ item }}
              </ComboboxItem>
            </ComboboxViewport>
          </ComboboxList>
        </Combobox>
        <FieldDescription>Please select a valid framework.</FieldDescription>
        <FieldError :errors="[{ message: 'This field is required.' }]" />
      </Field>
    </div>
  </Example>
</template>
