// examples/nextjs/src/components/progress-controlled.tsx
"use client";

import * as React from "react";

import { Progress } from "@line/abc-def-react/progress";
import { Slider } from "@line/abc-def-react/slider";

export function ProgressControlled() {
  const [value, setValue] = React.useState([50]);

  return (
    <div className="flex w-full max-w-sm flex-col gap-4">
      <Progress value={value[0]} />
      <Slider
        value={value}
        onValueChange={setValue}
        min={0}
        max={100}
        step={1}
      />
    </div>
  );
}

// examples/vue-vite/src/examples/progress/ProgressControlled.vue
<script setup lang="ts">
import { Progress } from "@line/abc-def-vue/progress";
import { Slider } from "@line/abc-def-vue/slider";
import { ref } from "vue";

import { Example } from "@/registry/bases/reka/components/example";

const value = ref([50]);
</script>

<template>
  <Example title="Controlled">
    <div class="flex w-full flex-col gap-4">
      <Progress :model-value="value[0]" class="w-full" />
      <Slider v-model="value" :min="0" :max="100" :step="1" />
    </div>
  </Example>
</template>
