// examples/nextjs/src/components/collapsible-settings.tsx
"use client";

import * as React from "react";
import { MaximizeIcon, MinimizeIcon } from "lucide-react";

import { Button } from "@line/abc-def-react/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@line/abc-def-react/card";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@line/abc-def-react/collapsible";
import { Field, FieldGroup, FieldLabel } from "@line/abc-def-react/field";
import { Input } from "@line/abc-def-react/input";

export function CollapsibleSettings() {
  const [isOpen, setIsOpen] = React.useState(false);

  return (
    <Card className="mx-auto w-full max-w-xs" size="sm">
      <CardHeader>
        <CardTitle>Radius</CardTitle>
        <CardDescription>Set the corner radius of the element.</CardDescription>
      </CardHeader>
      <CardContent>
        <Collapsible
          open={isOpen}
          onOpenChange={setIsOpen}
          className="flex items-start gap-2"
        >
          <FieldGroup className="grid w-full grid-cols-2 gap-2">
            <Field>
              <FieldLabel htmlFor="radius-x" className="sr-only">
                Radius X
              </FieldLabel>
              <Input id="radius" placeholder="0" defaultValue={0} />
            </Field>
            <Field>
              <FieldLabel htmlFor="radius-y" className="sr-only">
                Radius Y
              </FieldLabel>
              <Input id="radius" placeholder="0" defaultValue={0} />
            </Field>
            <CollapsibleContent className="col-span-full grid grid-cols-subgrid gap-2">
              <Field>
                <FieldLabel htmlFor="radius-x" className="sr-only">
                  Radius X
                </FieldLabel>
                <Input id="radius" placeholder="0" defaultValue={0} />
              </Field>
              <Field>
                <FieldLabel htmlFor="radius-y" className="sr-only">
                  Radius Y
                </FieldLabel>
                <Input id="radius" placeholder="0" defaultValue={0} />
              </Field>
            </CollapsibleContent>
          </FieldGroup>
          <CollapsibleTrigger asChild>
            <Button variant="outline" size="icon">
              {isOpen ? <MinimizeIcon /> : <MaximizeIcon />}
            </Button>
          </CollapsibleTrigger>
        </Collapsible>
      </CardContent>
    </Card>
  );
}

// examples/vue-vite/src/examples/collapsible/CollapsibleSettings.vue
<script setup lang="ts">
import { Button } from "@line/abc-def-vue/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@line/abc-def-vue/card";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@line/abc-def-vue/collapsible";
import { Field, FieldGroup, FieldLabel } from "@line/abc-def-vue/field";
import { Input } from "@line/abc-def-vue/input";
import { ref } from "vue";

import { Example } from "@/components/example";
import IconPlaceholder from "@/components/IconPlaceholder.vue";

const isOpen = ref(false);
</script>

<template>
  <Example title="Settings" class="items-center">
    <Card class="mx-auto w-full max-w-xs" size="sm">
      <CardHeader>
        <CardTitle>Radius</CardTitle>
        <CardDescription>
          Set the corner radius of the element.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Collapsible v-model:open="isOpen" class="flex items-start gap-2">
          <FieldGroup class="grid w-full grid-cols-2 gap-2">
            <Field>
              <FieldLabel html-for="radius-x" class="sr-only">
                Radius X
              </FieldLabel>
              <Input id="radius" placeholder="0" :default-value="0" />
            </Field>
            <Field>
              <FieldLabel html-for="radius-y" class="sr-only">
                Radius Y
              </FieldLabel>
              <Input id="radius" placeholder="0" :default-value="0" />
            </Field>
            <CollapsibleContent
              class="col-span-full grid grid-cols-subgrid gap-2"
            >
              <Field>
                <FieldLabel html-for="radius-x" class="sr-only">
                  Radius X
                </FieldLabel>
                <Input id="radius" placeholder="0" :default-value="0" />
              </Field>
              <Field>
                <FieldLabel html-for="radius-y" class="sr-only">
                  Radius Y
                </FieldLabel>
                <Input id="radius" placeholder="0" :default-value="0" />
              </Field>
            </CollapsibleContent>
          </FieldGroup>
          <CollapsibleTrigger :as-child="true">
            <Button variant="outline" size="icon">
              <IconPlaceholder
                v-if="isOpen"
                lucide="MinimizeIcon"
                tabler="IconMinimize"
                hugeicons="MinusSignIcon"
                phosphor="ArrowsInIcon"
                remixicon="RiContractLine"
              />
              <IconPlaceholder
                v-else
                lucide="MaximizeIcon"
                tabler="IconMaximize"
                hugeicons="PlusSignIcon"
                phosphor="ArrowsOutIcon"
                remixicon="RiExpandLine"
              />
            </Button>
          </CollapsibleTrigger>
        </Collapsible>
      </CardContent>
    </Card>
  </Example>
</template>
