// examples/vue-vite/src/examples/badge/BadgeVariants.vue
<script setup lang="ts">
import { Badge } from "@line/abc-def-vue/badge";

import { Example } from "@/components/example";
</script>

<template>
  <Example title="Variants">
    <div class="flex flex-wrap gap-2">
      <Badge>Default</Badge>
      <Badge variant="secondary"> Secondary </Badge>
      <Badge variant="destructive"> Destructive </Badge>
      <Badge variant="outline"> Outline </Badge>
      <Badge variant="ghost"> Ghost </Badge>
      <Badge variant="link"> Link </Badge>
    </div>
  </Example>
</template>

// examples/nextjs/src/components/badge-variants.tsx
import { Badge } from "@line/abc-def-react/badge";

export function BadgeVariants() {
  return (
    <div className="flex flex-wrap gap-2">
      <Badge>Default</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="destructive">Destructive</Badge>
      <Badge variant="outline">Outline</Badge>
      <Badge variant="ghost">Ghost</Badge>
    </div>
  );
}
