// examples/vue-vite/src/examples/calendar/CalendarBookedDates.vue
<script setup lang="ts">
import { Calendar } from "@line/abc-def-vue/calendar";
import { Card, CardContent } from "@line/abc-def-vue/card";
import { CalendarDate } from "@internationalized/date";
import { ref } from "vue";

import { Example } from "@/components/example";

const date = ref<CalendarDate>(
  new CalendarDate(new Date().getFullYear(), 2, 3),
);

const bookedDates = Array.from(
  { length: 15 },
  (_, i) => new CalendarDate(new Date().getFullYear(), 2, 12 + i),
);
</script>

<template>
  <Example title="Booked Dates">
    <Card class="mx-auto w-fit p-0">
      <CardContent class="p-0">
        <Calendar
          v-model="date as any"
          :disabled="bookedDates as any"
          :is-date-unavailable="
            (date) => bookedDates.some((d) => d.compare(date as any) === 0)
          "
        />
      </CardContent>
    </Card>
  </Example>
</template>

// examples/nextjs/src/components/calendar-booked-dates.tsx
"use client";

import * as React from "react";
import { es } from "react-day-picker/locale";

import { Calendar } from "@line/abc-def-react/calendar";
import { Card, CardContent } from "@line/abc-def-react/card";

export function CalendarBookedDates() {
  const [date, setDate] = React.useState<Date | undefined>(
    new Date(new Date().getFullYear(), 1, 3),
  );
  const bookedDates = Array.from(
    { length: 15 },
    (_, i) => new Date(new Date().getFullYear(), 1, 12 + i),
  );

  return (
    <Card className="mx-auto w-fit p-0">
      <CardContent className="p-0">
        <Calendar
          mode="single"
          defaultMonth={date}
          selected={date}
          onSelect={setDate}
          disabled={bookedDates}
          modifiers={{
            booked: bookedDates,
          }}
          modifiersClassNames={{
            booked: "[&>button]:line-through opacity-100",
          }}
        />
      </CardContent>
    </Card>
  );
}
