// examples/vue-vite/src/examples/calendar/CalendarRange.vue
<script setup lang="ts">
import type { DateRange } from "reka-ui";
import { Card, CardContent } from "@line/abc-def-vue/card";
import { RangeCalendar } from "@line/abc-def-vue/range-calendar";
import { CalendarDate } from "@internationalized/date";
import { ref } from "vue";

import { Example } from "@/components/example";

const dateRange = ref({
  start: new CalendarDate(new Date().getFullYear(), 1, 12),
  end: new CalendarDate(new Date().getFullYear(), 2, 11),
} as DateRange);
</script>

<template>
  <Example
    title="Range"
    container-class="lg:col-span-full 2xl:col-span-full"
    class="p-12"
  >
    <Card class="mx-auto w-fit p-0">
      <CardContent class="p-0">
        <RangeCalendar v-model="dateRange as any" :number-of-months="2" />
      </CardContent>
    </Card>
  </Example>
</template>

// examples/nextjs/src/components/calendar-range.tsx
"use client";

import * as React from "react";
import { addDays } from "date-fns";
import { type DateRange } from "react-day-picker";

import { Calendar } from "@line/abc-def-react/calendar";
import { Card, CardContent } from "@line/abc-def-react/card";

export function CalendarRange() {
  const [dateRange, setDateRange] = React.useState<DateRange | undefined>({
    from: new Date(new Date().getFullYear(), 0, 12),
    to: addDays(new Date(new Date().getFullYear(), 0, 12), 30),
  });

  return (
    <Card className="mx-auto w-fit p-0">
      <CardContent className="p-0">
        <Calendar
          mode="range"
          defaultMonth={dateRange?.from}
          selected={dateRange}
          onSelect={setDateRange}
          numberOfMonths={2}
          disabled={(date) =>
            date > new Date() || date < new Date("1900-01-01")
          }
        />
      </CardContent>
    </Card>
  );
}
