// examples/vue-vite/src/examples/calendar/CalendarWeekNumbers.vue
<script setup lang="ts">
import { Calendar } from "@line/abc-def-vue/calendar";
import { Card, CardContent } from "@line/abc-def-vue/card";
import { CalendarDate } from "@internationalized/date";
import { ref } from "vue";

import { Example } from "@/components/example";

const date = ref<CalendarDate>(
  new CalendarDate(new Date().getFullYear(), new Date().getMonth() + 1, 3),
);
</script>

<template>
  <Example title="Week Numbers" class="justify-center">
    <Card class="mx-auto w-fit p-0">
      <CardContent class="p-0">
        <Calendar v-model="date as any" :week-starts-on="1" show-week-number />
      </CardContent>
    </Card>
  </Example>
</template>

// examples/nextjs/src/components/calendar-week-numbers.tsx
"use client";

import * as React from "react";

import { Calendar } from "@line/abc-def-react/calendar";
import { Card, CardContent } from "@line/abc-def-react/card";

export function CalendarWeekNumbers() {
  const [date, setDate] = React.useState<Date | undefined>(
    new Date(new Date().getFullYear(), 1, 3),
  );

  return (
    <Card className="mx-auto w-fit p-0">
      <CardContent className="p-0">
        <Calendar
          mode="single"
          defaultMonth={date}
          selected={date}
          onSelect={setDate}
          showWeekNumber
        />
      </CardContent>
    </Card>
  );
}
