// examples/vue-vite/src/examples/checkbox/CheckboxInvalid.vue
<script setup lang="ts">
import { Checkbox } from "@line/abc-def-vue/checkbox";
import { Field, FieldGroup, FieldLabel } from "@line/abc-def-vue/field";

import { Example } from "@/components/example";
</script>

<template>
  <Example title="Invalid">
    <FieldGroup>
      <Field orientation="horizontal" data-invalid="true">
        <Checkbox id="terms-3" aria-invalid="true" />
        <FieldLabel html-for="terms-3">
          Accept terms and conditions
        </FieldLabel>
      </Field>
    </FieldGroup>
  </Example>
</template>

// examples/nextjs/src/components/checkbox-invalid.tsx
import { Checkbox } from "@line/abc-def-react/checkbox";
import { Field, FieldGroup, FieldLabel } from "@line/abc-def-react/field";

export function CheckboxInvalid() {
  return (
    <FieldGroup className="mx-auto w-56">
      <Field orientation="horizontal" data-invalid>
        <Checkbox
          id="terms-checkbox-invalid"
          name="terms-checkbox-invalid"
          aria-invalid
        />
        <FieldLabel htmlFor="terms-checkbox-invalid">
          Accept terms and conditions
        </FieldLabel>
      </Field>
    </FieldGroup>
  );
}
