// examples/vue-vite/src/examples/checkbox/CheckboxDisabled.vue
<script setup lang="ts">
import { Checkbox } from "@line/abc-def-vue/checkbox";
import { Field, FieldLabel } from "@line/abc-def-vue/field";

import { Example } from "@/components/example";
</script>

<template>
  <Example title="Disabled">
    <Field orientation="horizontal">
      <Checkbox id="toggle" disabled />
      <FieldLabel html-for="toggle"> Enable notifications </FieldLabel>
    </Field>
  </Example>
</template>

// examples/nextjs/src/components/checkbox-disabled.tsx
import { Checkbox } from "@line/abc-def-react/checkbox";
import { Field, FieldGroup, FieldLabel } from "@line/abc-def-react/field";

export function CheckboxDisabled() {
  return (
    <FieldGroup className="mx-auto w-56">
      <Field orientation="horizontal" data-disabled>
        <Checkbox
          id="toggle-checkbox-disabled"
          name="toggle-checkbox-disabled"
          disabled
        />
        <FieldLabel htmlFor="toggle-checkbox-disabled">
          Enable notifications
        </FieldLabel>
      </Field>
    </FieldGroup>
  );
}
