// examples/vue-vite/src/examples/dialog/DialogNoCloseButton.vue
<script setup lang="ts">
import { Button } from "@line/abc-def-vue/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@line/abc-def-vue/dialog";

import { Example } from "@/components/example";
</script>

<template>
  <Example title="No Close Button" class="items-center justify-center">
    <Dialog>
      <DialogTrigger :as-child="true">
        <Button variant="outline"> No Close Button </Button>
      </DialogTrigger>
      <DialogContent :show-close-button="false">
        <DialogHeader>
          <DialogTitle>No Close Button</DialogTitle>
          <DialogDescription>
            This dialog doesn't have a close button in the top-right corner.
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <DialogClose :as-child="true">
            <Button variant="outline"> Close </Button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </Example>
</template>

// examples/nextjs/src/components/dialog-no-close-button.tsx
import { Button } from "@line/abc-def-react/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@line/abc-def-react/dialog";

export function DialogNoCloseButton() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">No Close Button</Button>
      </DialogTrigger>
      <DialogContent showCloseButton={false}>
        <DialogHeader>
          <DialogTitle>No Close Button</DialogTitle>
          <DialogDescription>
            This dialog doesn&apos;t have a close button in the top-right
            corner.
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  );
}
