// examples/vue-vite/src/examples/progress/FileUploadList.vue
<script setup lang="ts">
import {
  Item,
  ItemActions,
  ItemContent,
  ItemGroup,
  ItemMedia,
  ItemTitle,
} from "@line/abc-def-vue/item";
import { Progress } from "@line/abc-def-vue/progress";
import { computed } from "vue";

import IconPlaceholder from "@/components/IconPlaceholder.vue";
import { Example } from "@/registry/bases/reka/components/example";

const files = computed(() => [
  {
    id: "1",
    name: "document.pdf",
    progress: 45,
    timeRemaining: "2m 30s",
  },
  {
    id: "2",
    name: "presentation.pptx",
    progress: 78,
    timeRemaining: "45s",
  },
  {
    id: "3",
    name: "spreadsheet.xlsx",
    progress: 12,
    timeRemaining: "5m 12s",
  },
  {
    id: "4",
    name: "image.jpg",
    progress: 100,
    timeRemaining: "Complete",
  },
]);
</script>

<template>
  <Example title="File Upload List">
    <ItemGroup>
      <Item v-for="file in files" :key="file.id" size="xs" class="px-0">
        <ItemMedia variant="icon">
          <IconPlaceholder
            lucide="FileIcon"
            tabler="IconFile"
            hugeicons="FileIcon"
            phosphor="FileIcon"
            remixicon="RiFileLine"
            class="size-5"
          />
        </ItemMedia>
        <ItemContent class="inline-block truncate">
          <ItemTitle class="inline">
            {{ file.name }}
          </ItemTitle>
        </ItemContent>
        <ItemContent>
          <Progress :model-value="file.progress" class="w-32" />
        </ItemContent>
        <ItemActions class="w-16 justify-end">
          <span class="text-muted-foreground text-sm">
            {{ file.timeRemaining }}
          </span>
        </ItemActions>
      </Item>
    </ItemGroup>
  </Example>
</template>

// examples/nextjs/src/components/file-upload-list.tsx
"use client";

import * as React from "react";
import { FileIcon } from "lucide-react";

import {
  Item,
  ItemActions,
  ItemContent,
  ItemGroup,
  ItemMedia,
  ItemTitle,
} from "@line/abc-def-react/item";
import { Progress } from "@line/abc-def-react/progress";

export function FileUploadList() {
  const files = React.useMemo(
    () => [
      {
        id: "1",
        name: "document.pdf",
        progress: 45,
        timeRemaining: "2m 30s",
      },
      {
        id: "2",
        name: "presentation.pptx",
        progress: 78,
        timeRemaining: "45s",
      },
      {
        id: "3",
        name: "spreadsheet.xlsx",
        progress: 12,
        timeRemaining: "5m 12s",
      },
      {
        id: "4",
        name: "image.jpg",
        progress: 100,
        timeRemaining: "Complete",
      },
    ],
    [],
  );

  return (
    <ItemGroup>
      {files.map((file) => (
        <Item key={file.id} size="xs" className="px-0">
          <ItemMedia variant="icon">
            <FileIcon className="size-5" />
          </ItemMedia>
          <ItemContent className="inline-block truncate">
            <ItemTitle className="inline">{file.name}</ItemTitle>
          </ItemContent>
          <ItemContent>
            <Progress value={file.progress} className="w-32" />
          </ItemContent>
          <ItemActions className="w-16 justify-end">
            <span className="text-muted-foreground text-sm">
              {file.timeRemaining}
            </span>
          </ItemActions>
        </Item>
      ))}
    </ItemGroup>
  );
}
