// examples/vue-vite/src/examples/hover-card/HoverCardSides.vue
<script setup lang="ts">
import { Button } from "@line/abc-def-vue/button";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@line/abc-def-vue/hover-card";

import { Example } from "@/registry/bases/reka/components/example";

const HOVER_CARD_SIDES = ["top", "right", "bottom", "left"] as const;
</script>

<template>
  <Example title="Sides">
    <div class="flex flex-wrap items-center justify-center gap-4">
      <HoverCard
        v-for="side in HOVER_CARD_SIDES"
        :key="side"
        :open-delay="100"
        :close-delay="100"
      >
        <HoverCardTrigger :as-child="true">
          <Button variant="outline" class="capitalize">
            {{ side }}
          </Button>
        </HoverCardTrigger>
        <HoverCardContent :side="side" class="w-64">
          <div
            class="style-lyra:gap-1 style-vega:gap-2 style-maia:gap-2 style-mira:gap-1 flex flex-col gap-1.5"
          >
            <h4 class="font-medium">Hover Card</h4>
            <p>
              This hover card appears on the {{ side }} side of the trigger.
            </p>
          </div>
        </HoverCardContent>
      </HoverCard>
    </div>
  </Example>
</template>

// examples/nextjs/src/components/hover-card-sides.tsx
import { Button } from "@line/abc-def-react/button";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@line/abc-def-react/hover-card";

const HOVER_CARD_SIDES = ["left", "top", "bottom", "right"] as const;

export function HoverCardSides() {
  return (
    <div className="flex flex-wrap justify-center gap-2">
      {HOVER_CARD_SIDES.map((side) => (
        <HoverCard key={side} openDelay={100} closeDelay={100}>
          <HoverCardTrigger asChild>
            <Button variant="outline" className="capitalize">
              {side}
            </Button>
          </HoverCardTrigger>
          <HoverCardContent side={side}>
            <div className="flex flex-col gap-1">
              <h4 className="font-medium">Hover Card</h4>
              <p>This hover card appears on the {side} side of the trigger.</p>
            </div>
          </HoverCardContent>
        </HoverCard>
      ))}
    </div>
  );
}
