// examples/vue-vite/src/examples/popover/PopoverAlignments.vue
<script setup lang="ts">
import { Button } from "@line/abc-def-vue/button";
import { Popover, PopoverContent, PopoverTrigger } from "@line/abc-def-vue/popover";
</script>

<template>
  <div class="flex gap-6">
    <Popover>
      <PopoverTrigger :as-child="true">
        <Button variant="outline" size="sm"> Start </Button>
      </PopoverTrigger>
      <PopoverContent align="start" class="w-40">
        Aligned to start
      </PopoverContent>
    </Popover>
    <Popover>
      <PopoverTrigger :as-child="true">
        <Button variant="outline" size="sm"> Center </Button>
      </PopoverTrigger>
      <PopoverContent align="center" class="w-40">
        Aligned to center
      </PopoverContent>
    </Popover>
    <Popover>
      <PopoverTrigger :as-child="true">
        <Button variant="outline" size="sm"> End </Button>
      </PopoverTrigger>
      <PopoverContent align="end" class="w-40"> Aligned to end </PopoverContent>
    </Popover>
  </div>
</template>

// examples/nextjs/src/components/popover-alignments.tsx
import { Button } from "@line/abc-def-react/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@line/abc-def-react/popover";

export function PopoverAlignments() {
  return (
    <div className="flex gap-6">
      <Popover>
        <PopoverTrigger asChild>
          <Button variant="outline" size="sm">
            Start
          </Button>
        </PopoverTrigger>
        <PopoverContent align="start" className="w-40">
          Aligned to start
        </PopoverContent>
      </Popover>
      <Popover>
        <PopoverTrigger asChild>
          <Button variant="outline" size="sm">
            Center
          </Button>
        </PopoverTrigger>
        <PopoverContent align="center" className="w-40">
          Aligned to center
        </PopoverContent>
      </Popover>
      <Popover>
        <PopoverTrigger asChild>
          <Button variant="outline" size="sm">
            End
          </Button>
        </PopoverTrigger>
        <PopoverContent align="end" className="w-40">
          Aligned to end
        </PopoverContent>
      </Popover>
    </div>
  );
}
