// examples/vue-vite/src/examples/radio-group/RadioGroupInvalid.vue
<script setup lang="ts">
import {
  Field,
  FieldDescription,
  FieldLabel,
  FieldLegend,
  FieldSet,
} from "@line/abc-def-vue/field";
import { RadioGroup, RadioGroupItem } from "@line/abc-def-vue/radio-group";
</script>

<template>
  <FieldSet>
    <FieldLegend>Notification Preferences</FieldLegend>
    <FieldDescription>
      Choose how you want to receive notifications.
    </FieldDescription>
    <RadioGroup default-value="email">
      <Field orientation="horizontal" data-invalid>
        <RadioGroupItem id="invalid-email" value="email" :aria-invalid="true" />
        <FieldLabel for="invalid-email" class="font-normal">
          Email only
        </FieldLabel>
      </Field>
      <Field orientation="horizontal" data-invalid>
        <RadioGroupItem id="invalid-sms" value="sms" :aria-invalid="true" />
        <FieldLabel for="invalid-sms" class="font-normal">
          SMS only
        </FieldLabel>
      </Field>
      <Field orientation="horizontal" data-invalid>
        <RadioGroupItem id="invalid-both" value="both" :aria-invalid="true" />
        <FieldLabel for="invalid-both" class="font-normal">
          Both Email & SMS
        </FieldLabel>
      </Field>
    </RadioGroup>
  </FieldSet>
</template>

// examples/nextjs/src/components/radio-group-invalid.tsx
import {
  Field,
  FieldDescription,
  FieldLabel,
  FieldLegend,
  FieldSet,
} from "@line/abc-def-react/field";
import { RadioGroup, RadioGroupItem } from "@line/abc-def-react/radio-group";

export function RadioGroupInvalid() {
  return (
    <FieldSet className="w-full max-w-xs">
      <FieldLegend variant="label">Notification Preferences</FieldLegend>
      <FieldDescription>
        Choose how you want to receive notifications.
      </FieldDescription>
      <RadioGroup defaultValue="email">
        <Field orientation="horizontal" data-invalid>
          <RadioGroupItem value="email" id="invalid-email" aria-invalid />
          <FieldLabel htmlFor="invalid-email" className="font-normal">
            Email only
          </FieldLabel>
        </Field>
        <Field orientation="horizontal" data-invalid>
          <RadioGroupItem value="sms" id="invalid-sms" aria-invalid />
          <FieldLabel htmlFor="invalid-sms" className="font-normal">
            SMS only
          </FieldLabel>
        </Field>
        <Field orientation="horizontal" data-invalid>
          <RadioGroupItem value="both" id="invalid-both" aria-invalid />
          <FieldLabel htmlFor="invalid-both" className="font-normal">
            Both Email & SMS
          </FieldLabel>
        </Field>
      </RadioGroup>
    </FieldSet>
  );
}
