// examples/vue-vite/src/examples/radio-group/RadioGroupDisabled.vue
<script setup lang="ts">
import { Field, FieldLabel } from "@line/abc-def-vue/field";
import { RadioGroup, RadioGroupItem } from "@line/abc-def-vue/radio-group";
</script>

<template>
  <RadioGroup default-value="option2" :disabled="true">
    <Field orientation="horizontal">
      <RadioGroupItem id="disabled-1" value="option1" />
      <FieldLabel html-for="disabled-1" class="font-normal">
        Option 1
      </FieldLabel>
    </Field>
    <Field orientation="horizontal">
      <RadioGroupItem id="disabled-2" value="option2" />
      <FieldLabel html-for="disabled-2" class="font-normal">
        Option 2
      </FieldLabel>
    </Field>
    <Field orientation="horizontal">
      <RadioGroupItem id="disabled-3" value="option3" />
      <FieldLabel html-for="disabled-3" class="font-normal">
        Option 3
      </FieldLabel>
    </Field>
  </RadioGroup>
</template>

// examples/nextjs/src/components/radio-group-disabled.tsx
import { Field, FieldLabel } from "@line/abc-def-react/field";
import { RadioGroup, RadioGroupItem } from "@line/abc-def-react/radio-group";

export function RadioGroupDisabled() {
  return (
    <RadioGroup defaultValue="option2" className="w-fit">
      <Field orientation="horizontal" data-disabled>
        <RadioGroupItem value="option1" id="disabled-1" disabled />
        <FieldLabel htmlFor="disabled-1" className="font-normal">
          Disabled
        </FieldLabel>
      </Field>
      <Field orientation="horizontal">
        <RadioGroupItem value="option2" id="disabled-2" />
        <FieldLabel htmlFor="disabled-2" className="font-normal">
          Option 2
        </FieldLabel>
      </Field>
      <Field orientation="horizontal">
        <RadioGroupItem value="option3" id="disabled-3" />
        <FieldLabel htmlFor="disabled-3" className="font-normal">
          Option 3
        </FieldLabel>
      </Field>
    </RadioGroup>
  );
}
