// examples/vue-vite/src/examples/slider/SliderControlled.vue
<script setup lang="ts">
import { Label } from "@line/abc-def-vue/label";
import { Slider } from "@line/abc-def-vue/slider";
import { ref } from "vue";

const value = ref([0.3, 0.7]);
</script>

<template>
  <div class="grid w-full gap-3">
    <div class="flex items-center justify-between gap-2">
      <Label html-for="slider-demo-temperature">Temperature</Label>
      <span class="text-muted-foreground text-sm">
        {{ value.join(", ") }}
      </span>
    </div>
    <Slider
      id="slider-demo-temperature"
      v-model="value"
      :min="0"
      :max="1"
      :step="0.1"
    />
  </div>
</template>

// examples/nextjs/src/components/slider-controlled.tsx
"use client";

import * as React from "react";

import { Label } from "@line/abc-def-react/label";
import { Slider } from "@line/abc-def-react/slider";

export function SliderControlled() {
  const [value, setValue] = React.useState([0.3, 0.7]);

  return (
    <div className="mx-auto grid w-full max-w-xs gap-3">
      <div className="flex items-center justify-between gap-2">
        <Label htmlFor="slider-demo-temperature">Temperature</Label>
        <span className="text-muted-foreground text-sm">
          {value.join(", ")}
        </span>
      </div>
      <Slider
        id="slider-demo-temperature"
        value={value}
        onValueChange={setValue}
        min={0}
        max={1}
        step={0.1}
      />
    </div>
  );
}
