// examples/vue-vite/src/examples/switch/SwitchDisabled.vue
<script setup lang="ts">
import { Label } from "@line/abc-def-vue/label";
import { Switch } from "@line/abc-def-vue/switch";
</script>

<template>
  <div class="flex flex-col gap-12">
    <div class="flex items-center gap-2">
      <Switch id="switch-disabled-unchecked" :disabled="true" />
      <Label html-for="switch-disabled-unchecked"> Disabled (Unchecked) </Label>
    </div>
    <div class="flex items-center gap-2">
      <Switch
        id="switch-disabled-checked"
        :default-checked="true"
        :disabled="true"
      />
      <Label html-for="switch-disabled-checked"> Disabled (Checked) </Label>
    </div>
  </div>
</template>

// examples/nextjs/src/components/switch-disabled.tsx
import { Field, FieldLabel } from "@line/abc-def-react/field";
import { Switch } from "@line/abc-def-react/switch";

export function SwitchDisabled() {
  return (
    <Field orientation="horizontal" data-disabled className="w-fit">
      <Switch id="switch-disabled-unchecked" disabled />
      <FieldLabel htmlFor="switch-disabled-unchecked">Disabled</FieldLabel>
    </Field>
  );
}
