// examples/vue-vite/src/examples/tabs/TabsLine.vue
<script setup lang="ts">
import { Tabs, TabsList, TabsTrigger } from "@line/abc-def-vue/tabs";
</script>

<template>
  <Tabs default-value="overview">
    <TabsList variant="line">
      <TabsTrigger value="overview"> Overview </TabsTrigger>
      <TabsTrigger value="analytics"> Analytics </TabsTrigger>
      <TabsTrigger value="reports"> Reports </TabsTrigger>
    </TabsList>
  </Tabs>
</template>

// examples/nextjs/src/components/tabs-line.tsx
import { Tabs, TabsList, TabsTrigger } from "@line/abc-def-react/tabs";

export function TabsLine() {
  return (
    <Tabs defaultValue="overview">
      <TabsList variant="line">
        <TabsTrigger value="overview">Overview</TabsTrigger>
        <TabsTrigger value="analytics">Analytics</TabsTrigger>
        <TabsTrigger value="reports">Reports</TabsTrigger>
      </TabsList>
    </Tabs>
  );
}
