// examples/vue-vite/src/examples/tabs/TabsDisabled.vue
<script setup lang="ts">
import { Tabs, TabsList, TabsTrigger } from "@line/abc-def-vue/tabs";
</script>

<template>
  <Tabs default-value="home">
    <TabsList>
      <TabsTrigger value="home"> Home </TabsTrigger>
      <TabsTrigger value="settings" :disabled="true"> Disabled </TabsTrigger>
    </TabsList>
  </Tabs>
</template>

// examples/nextjs/src/components/tabs-disabled.tsx
import { Tabs, TabsList, TabsTrigger } from "@line/abc-def-react/tabs";

export function TabsDisabled() {
  return (
    <Tabs defaultValue="home">
      <TabsList>
        <TabsTrigger value="home">Home</TabsTrigger>
        <TabsTrigger value="settings" disabled>
          Disabled
        </TabsTrigger>
      </TabsList>
    </Tabs>
  );
}
