// examples/vue-vite/src/examples/textarea/TextareaDisabled.vue
<script setup lang="ts">
import { Field, FieldLabel } from "@line/abc-def-vue/field";
import { Textarea } from "@line/abc-def-vue/textarea";
</script>

<template>
  <Field>
    <FieldLabel html-for="textarea-demo-disabled"> Message </FieldLabel>
    <Textarea
      id="textarea-demo-disabled"
      placeholder="Type your message here."
      :disabled="true"
    />
  </Field>
</template>

// examples/nextjs/src/components/textarea-disabled.tsx
import { Field, FieldLabel } from "@line/abc-def-react/field";
import { Textarea } from "@line/abc-def-react/textarea";

export function TextareaDisabled() {
  return (
    <Field data-disabled>
      <FieldLabel htmlFor="textarea-disabled">Message</FieldLabel>
      <Textarea
        id="textarea-disabled"
        placeholder="Type your message here."
        disabled
      />
    </Field>
  );
}
