// examples/nextjs/src/components/alert-basic.tsx
import { CheckCircle2Icon } from "lucide-react";

import { Alert, AlertDescription, AlertTitle } from "@line/abc-def-react/alert";

export default function AlertBasic() {
  return (
    <Alert className="max-w-md">
      <CheckCircle2Icon />
      <AlertTitle>Account updated successfully</AlertTitle>
      <AlertDescription>
        Your profile information has been saved. Changes will be reflected
        immediately.
      </AlertDescription>
    </Alert>
  );
}

// examples/vue-vite/src/examples/alert/AlertBasic.vue
<script setup lang="ts">
import { Alert, AlertDescription, AlertTitle } from "@line/abc-def-vue/alert";

import { Example } from "@/components/example";
</script>

<template>
  <Example title="Basic">
    <div class="mx-auto flex w-full max-w-lg flex-col gap-4">
      <Alert>
        <AlertTitle>Success! Your changes have been saved.</AlertTitle>
      </Alert>
      <Alert>
        <AlertTitle>Success! Your changes have been saved.</AlertTitle>
        <AlertDescription>
          This is an alert with title and description.
        </AlertDescription>
      </Alert>
      <Alert>
        <AlertDescription>
          This one has a description only. No title. No icon.
        </AlertDescription>
      </Alert>
    </div>
  </Example>
</template>
